var annotated_dup =
[
    [ "Key Features", "md_README.html#autotoc_md8", null ],
    [ "Build", "md_README.html#autotoc_md9", [
      [ "Download", "md_README.html#autotoc_md10", null ],
      [ "Configure", "md_README.html#autotoc_md11", [
        [ "Cross-Compilation", "md_README.html#autotoc_md12", null ],
        [ "CMake Arguments", "md_README.html#autotoc_md13", null ]
      ] ],
      [ "Build", "md_README.html#autotoc_md14", null ],
      [ "Note on alignment", "md_README.html#autotoc_md15", null ]
    ] ],
    [ "Contributing to this project", "md_README.html#autotoc_md16", null ],
    [ "Documentation", "md_README.html#autotoc_md17", null ],
    [ "Related", "md_README.html#autotoc_md18", null ],
    [ "License", "md_README.html#autotoc_md19", null ],
    [ "__AuthInfo", "struct____AuthInfo.html", "struct____AuthInfo" ],
    [ "__ClientCallbacks", "struct____ClientCallbacks.html", "struct____ClientCallbacks" ],
    [ "__ClientInfo", "struct____ClientInfo.html", "struct____ClientInfo" ],
    [ "__ClientInfo_V0", "struct____ClientInfo__V0.html", "struct____ClientInfo__V0" ],
    [ "__ClientMetrics", "struct____ClientMetrics.html", "struct____ClientMetrics" ],
    [ "__ContentView", "struct____ContentView.html", "struct____ContentView" ],
    [ "__CurrentViewItem", "struct____CurrentViewItem.html", "struct____CurrentViewItem" ],
    [ "__DeviceInfo", "struct____DeviceInfo.html", "struct____DeviceInfo" ],
    [ "__DeviceInfo_V0", "struct____DeviceInfo__V0.html", "struct____DeviceInfo__V0" ],
    [ "__DoubleListNode", "struct____DoubleListNode.html", "struct____DoubleListNode" ],
    [ "__EndpointInfo", "struct____EndpointInfo.html", "struct____EndpointInfo" ],
    [ "__ExponentialBackoffRetryStrategyConfig", "struct____ExponentialBackoffRetryStrategyConfig.html", "struct____ExponentialBackoffRetryStrategyConfig" ],
    [ "__FragmentAck", "struct____FragmentAck.html", "struct____FragmentAck" ],
    [ "__FragmentAckParser", "struct____FragmentAckParser.html", "struct____FragmentAckParser" ],
    [ "__FragmentMetadata", "struct____FragmentMetadata.html", "struct____FragmentMetadata" ],
    [ "__Frame", "struct____Frame.html", "struct____Frame" ],
    [ "__FrameOrderCoordinator", "struct____FrameOrderCoordinator.html", "struct____FrameOrderCoordinator" ],
    [ "__FrameOrderTrackData", "struct____FrameOrderTrackData.html", "struct____FrameOrderTrackData" ],
    [ "__KinesisVideoBase", "struct____KinesisVideoBase.html", "struct____KinesisVideoBase" ],
    [ "__KinesisVideoClient", "struct____KinesisVideoClient.html", "struct____KinesisVideoClient" ],
    [ "__KinesisVideoStream", "struct____KinesisVideoStream.html", "struct____KinesisVideoStream" ],
    [ "__KinesisVideoStreamDiagnostics", "struct____KinesisVideoStreamDiagnostics.html", "struct____KinesisVideoStreamDiagnostics" ],
    [ "__KvsRetryStrategy", "struct____KvsRetryStrategy.html", "struct____KvsRetryStrategy" ],
    [ "__KvsRetryStrategyCallbacks", "struct____KvsRetryStrategyCallbacks.html", "struct____KvsRetryStrategyCallbacks" ],
    [ "__MetadataTracker", "struct____MetadataTracker.html", "struct____MetadataTracker" ],
    [ "__MkvGenerator", "struct____MkvGenerator.html", "struct____MkvGenerator" ],
    [ "__SecurityTokenInfo", "struct____SecurityTokenInfo.html", "struct____SecurityTokenInfo" ],
    [ "__SegmentInfo", "struct____SegmentInfo.html", "struct____SegmentInfo" ],
    [ "__SerializedMetadata", "struct____SerializedMetadata.html", "struct____SerializedMetadata" ],
    [ "__ServiceCallContext", "struct____ServiceCallContext.html", "struct____ServiceCallContext" ],
    [ "__SingleListNode", "struct____SingleListNode.html", "struct____SingleListNode" ],
    [ "__StateMachine", "struct____StateMachine.html", "struct____StateMachine" ],
    [ "__StateMachineContext", "struct____StateMachineContext.html", "struct____StateMachineContext" ],
    [ "__StateMachineImpl", "struct____StateMachineImpl.html", "struct____StateMachineImpl" ],
    [ "__StateMachineState", "struct____StateMachineState.html", "struct____StateMachineState" ],
    [ "__StorageInfo", "struct____StorageInfo.html", "struct____StorageInfo" ],
    [ "__StreamCaps", "struct____StreamCaps.html", "struct____StreamCaps" ],
    [ "__StreamDescription", "struct____StreamDescription.html", "struct____StreamDescription" ],
    [ "__StreamDescription_V0", "struct____StreamDescription__V0.html", "struct____StreamDescription__V0" ],
    [ "__StreamEventMetadata", "struct____StreamEventMetadata.html", "struct____StreamEventMetadata" ],
    [ "__StreamInfo", "struct____StreamInfo.html", "struct____StreamInfo" ],
    [ "__StreamMetrics", "struct____StreamMetrics.html", "struct____StreamMetrics" ],
    [ "__Tag", "struct____Tag.html", "struct____Tag" ],
    [ "__ThreadData", "struct____ThreadData.html", "struct____ThreadData" ],
    [ "__Threadpool", "struct____Threadpool.html", "struct____Threadpool" ],
    [ "__UploadHandleInfo", "struct____UploadHandleInfo.html", "struct____UploadHandleInfo" ],
    [ "AIV_ALLOCATION_HEADER", "structAIV__ALLOCATION__HEADER.html", "structAIV__ALLOCATION__HEADER" ],
    [ "AivHeap", "structAivHeap.html", "structAivHeap" ],
    [ "ALLOCATION_FOOTER", "structALLOCATION__FOOTER.html", "structALLOCATION__FOOTER" ],
    [ "ALLOCATION_HEADER", "structALLOCATION__HEADER.html", "structALLOCATION__HEADER" ],
    [ "BaseHeap", "structBaseHeap.html", "structBaseHeap" ],
    [ "BitField", "structBitField.html", "structBitField" ],
    [ "BitReader", "structBitReader.html", "structBitReader" ],
    [ "DoubleList", "structDoubleList.html", "structDoubleList" ],
    [ "DurationState", "structDurationState.html", "structDurationState" ],
    [ "EncodedFrameInfo", "structEncodedFrameInfo.html", "structEncodedFrameInfo" ],
    [ "ExponentialBackoffRetryStrategyState", "structExponentialBackoffRetryStrategyState.html", "structExponentialBackoffRetryStrategyState" ],
    [ "FileLogger", "structFileLogger.html", "structFileLogger" ],
    [ "FileLoggerParameters", "structFileLoggerParameters.html", "structFileLoggerParameters" ],
    [ "H265SpsInfo", "structH265SpsInfo.html", "structH265SpsInfo" ],
    [ "HashBucket", "structHashBucket.html", "structHashBucket" ],
    [ "HashEntry", "structHashEntry.html", "structHashEntry" ],
    [ "HashTable", "structHashTable.html", "structHashTable" ],
    [ "Heap", "structHeap.html", "structHeap" ],
    [ "HybridFileHeap", "structHybridFileHeap.html", "structHybridFileHeap" ],
    [ "HybridHeap", "structHybridHeap.html", "structHybridHeap" ],
    [ "ParserState", "structParserState.html", "structParserState" ],
    [ "RollingContentView", "structRollingContentView.html", "structRollingContentView" ],
    [ "SafeBlockingQueue", "structSafeBlockingQueue.html", "structSafeBlockingQueue" ],
    [ "Semaphore", "structSemaphore.html", "structSemaphore" ],
    [ "SingleList", "structSingleList.html", "structSingleList" ],
    [ "StreamMkvGenerator", "structStreamMkvGenerator.html", "structStreamMkvGenerator" ],
    [ "TaskData", "structTaskData.html", "structTaskData" ],
    [ "TimerEntry", "structTimerEntry.html", "structTimerEntry" ],
    [ "TimerQueue", "structTimerQueue.html", "structTimerQueue" ],
    [ "Trace", "structTrace.html", "structTrace" ],
    [ "TraceProfiler", "structTraceProfiler.html", "structTraceProfiler" ],
    [ "TrackAudioConfig", "structTrackAudioConfig.html", "structTrackAudioConfig" ],
    [ "TrackCustomData", "unionTrackCustomData.html", "unionTrackCustomData" ],
    [ "TrackInfo", "structTrackInfo.html", "structTrackInfo" ],
    [ "TrackVideoConfig", "structTrackVideoConfig.html", "structTrackVideoConfig" ],
    [ "ViewItem", "structViewItem.html", "structViewItem" ],
    [ "WindowsThreadRoutineWrapper", "structWindowsThreadRoutineWrapper.html", "structWindowsThreadRoutineWrapper" ]
];