var hierarchy =
[
    [ "__AuthInfo", "struct____AuthInfo.html", null ],
    [ "__ClientCallbacks", "struct____ClientCallbacks.html", null ],
    [ "__ClientInfo", "struct____ClientInfo.html", null ],
    [ "__ClientInfo_V0", "struct____ClientInfo__V0.html", null ],
    [ "__ClientMetrics", "struct____ClientMetrics.html", null ],
    [ "__ContentView", "struct____ContentView.html", null ],
    [ "__CurrentViewItem", "struct____CurrentViewItem.html", null ],
    [ "__DeviceInfo", "struct____DeviceInfo.html", null ],
    [ "__DeviceInfo_V0", "struct____DeviceInfo__V0.html", null ],
    [ "__DoubleListNode", "struct____DoubleListNode.html", null ],
    [ "__EndpointInfo", "struct____EndpointInfo.html", null ],
    [ "__ExponentialBackoffRetryStrategyConfig", "struct____ExponentialBackoffRetryStrategyConfig.html", null ],
    [ "__FragmentAck", "struct____FragmentAck.html", null ],
    [ "__FragmentAckParser", "struct____FragmentAckParser.html", null ],
    [ "__FragmentMetadata", "struct____FragmentMetadata.html", null ],
    [ "__Frame", "struct____Frame.html", null ],
    [ "__FrameOrderCoordinator", "struct____FrameOrderCoordinator.html", null ],
    [ "__FrameOrderTrackData", "struct____FrameOrderTrackData.html", null ],
    [ "__KinesisVideoBase", "struct____KinesisVideoBase.html", null ],
    [ "__KinesisVideoClient", "struct____KinesisVideoClient.html", null ],
    [ "__KinesisVideoStream", "struct____KinesisVideoStream.html", null ],
    [ "__KinesisVideoStreamDiagnostics", "struct____KinesisVideoStreamDiagnostics.html", null ],
    [ "__KvsRetryStrategy", "struct____KvsRetryStrategy.html", null ],
    [ "__KvsRetryStrategyCallbacks", "struct____KvsRetryStrategyCallbacks.html", null ],
    [ "__MetadataTracker", "struct____MetadataTracker.html", null ],
    [ "__MkvGenerator", "struct____MkvGenerator.html", null ],
    [ "__Range", "struct____Range.html", null ],
    [ "__SecurityTokenInfo", "struct____SecurityTokenInfo.html", null ],
    [ "__SegmentInfo", "struct____SegmentInfo.html", null ],
    [ "__SerializedMetadata", "struct____SerializedMetadata.html", null ],
    [ "__ServiceCallContext", "struct____ServiceCallContext.html", null ],
    [ "__SingleListNode", "struct____SingleListNode.html", null ],
    [ "__StateMachine", "struct____StateMachine.html", null ],
    [ "__StateMachineContext", "struct____StateMachineContext.html", null ],
    [ "__StateMachineImpl", "struct____StateMachineImpl.html", null ],
    [ "__StateMachineState", "struct____StateMachineState.html", null ],
    [ "__StorageInfo", "struct____StorageInfo.html", null ],
    [ "__StreamCaps", "struct____StreamCaps.html", null ],
    [ "__StreamDescription", "struct____StreamDescription.html", null ],
    [ "__StreamDescription_V0", "struct____StreamDescription__V0.html", null ],
    [ "__StreamEventMetadata", "struct____StreamEventMetadata.html", null ],
    [ "__StreamInfo", "struct____StreamInfo.html", null ],
    [ "__StreamMetrics", "struct____StreamMetrics.html", null ],
    [ "__Tag", "struct____Tag.html", null ],
    [ "__ThreadData", "struct____ThreadData.html", null ],
    [ "__Threadpool", "struct____Threadpool.html", null ],
    [ "__UploadHandleInfo", "struct____UploadHandleInfo.html", null ],
    [ "AckItem", "structAckItem.html", null ],
    [ "AckItemComparator", "classAckItemComparator.html", null ],
    [ "AIV_ALLOCATION_HEADER", "structAIV__ALLOCATION__HEADER.html", null ],
    [ "AivHeap", "structAivHeap.html", null ],
    [ "ALLOCATION_FOOTER", "structALLOCATION__FOOTER.html", null ],
    [ "ALLOCATION_HEADER", "structALLOCATION__HEADER.html", null ],
    [ "BaseHeap", "structBaseHeap.html", null ],
    [ "BitField", "structBitField.html", null ],
    [ "BitReader", "structBitReader.html", null ],
    [ "DoubleList", "structDoubleList.html", null ],
    [ "DurationState", "structDurationState.html", null ],
    [ "EncodedFrameInfo", "structEncodedFrameInfo.html", null ],
    [ "ExponentialBackoffRetryStrategyState", "structExponentialBackoffRetryStrategyState.html", null ],
    [ "FileLogger", "structFileLogger.html", null ],
    [ "FileLoggerParameters", "structFileLoggerParameters.html", null ],
    [ "H265SpsInfo", "structH265SpsInfo.html", null ],
    [ "HashBucket", "structHashBucket.html", null ],
    [ "HashEntry", "structHashEntry.html", null ],
    [ "HashTable", "structHashTable.html", null ],
    [ "Heap", "structHeap.html", null ],
    [ "HybridFileHeap", "structHybridFileHeap.html", null ],
    [ "HybridHeap", "structHybridHeap.html", null ],
    [ "MockConsumer", "classMockConsumer.html", null ],
    [ "MockConsumerConfig", "structMockConsumerConfig.html", null ],
    [ "MockProducer", "classMockProducer.html", null ],
    [ "MockProducerConfig", "structMockProducerConfig.html", null ],
    [ "ParserState", "structParserState.html", null ],
    [ "RollingContentView", "structRollingContentView.html", null ],
    [ "SafeBlockingQueue", "structSafeBlockingQueue.html", null ],
    [ "SafeQueueUser", "structSafeQueueUser.html", null ],
    [ "Semaphore", "structSemaphore.html", null ],
    [ "SingleList", "structSingleList.html", null ],
    [ "StateTransitionsHookFunctionMetadata", "structStateTransitionsHookFunctionMetadata.html", null ],
    [ "StreamingSession", "classStreamingSession.html", null ],
    [ "StreamMkvGenerator", "structStreamMkvGenerator.html", null ],
    [ "TaskData", "structTaskData.html", null ],
    [ "Test", null, [
      [ "ClientTestBase", "classClientTestBase.html", [
        [ "AcksFunctionalityTest", "classAcksFunctionalityTest.html", null ],
        [ "CallbacksAndPressuresFunctionalityTest", "classCallbacksAndPressuresFunctionalityTest.html", null ],
        [ "ClientApiFunctionalityTest", "classClientApiFunctionalityTest.html", null ],
        [ "ClientApiTest", "classClientApiTest.html", null ],
        [ "ClientFunctionalityTest", "classClientFunctionalityTest.html", null ],
        [ "FrameOrderCoordinatorTest", "classFrameOrderCoordinatorTest.html", null ],
        [ "IntermittentProducerAutomaticStreamingTest", "classIntermittentProducerAutomaticStreamingTest.html", null ],
        [ "IntermittentProducerFunctionalityTest", "classIntermittentProducerFunctionalityTest.html", null ],
        [ "StateTransitionFunctionalityTest", "classStateTransitionFunctionalityTest.html", null ],
        [ "StreamApiFunctionalityScenarioTest", "classStreamApiFunctionalityScenarioTest.html", null ],
        [ "StreamApiFunctionalityTest", "classStreamApiFunctionalityTest.html", null ],
        [ "StreamApiServiceCallsTest", "classStreamApiServiceCallsTest.html", null ],
        [ "StreamApiTest", "classStreamApiTest.html", null ],
        [ "StreamDeviceTagsTest", "classStreamDeviceTagsTest.html", null ],
        [ "StreamFunctionalityTest", "classStreamFunctionalityTest.html", null ],
        [ "StreamParallelTest", "classStreamParallelTest.html", null ],
        [ "StreamPutGetTest", "classStreamPutGetTest.html", null ],
        [ "StreamRecoveryFunctionalityTest", "classStreamRecoveryFunctionalityTest.html", null ],
        [ "StreamStateTransitionsTest", "classStreamStateTransitionsTest.html", null ],
        [ "StreamStoppingFunctionalityTest", "classStreamStoppingFunctionalityTest.html", null ],
        [ "StreamTokenRotationTest", "classStreamTokenRotationTest.html", null ],
        [ "TokenRotationFunctionalityTest", "classTokenRotationFunctionalityTest.html", null ]
      ] ],
      [ "HeapTestBase", "classHeapTestBase.html", [
        [ "HeapApiFunctionalityTest", "classHeapApiFunctionalityTest.html", null ],
        [ "HeapApiTest", "classHeapApiTest.html", null ],
        [ "HeapPerfTest", "classHeapPerfTest.html", null ],
        [ "HybridFileHeapTest", "classHybridFileHeapTest.html", null ],
        [ "HybridHeapTest", "classHybridHeapTest.html", null ]
      ] ],
      [ "MkvgenTestBase", "classMkvgenTestBase.html", [
        [ "AnnexBCpdNalAdapterTest", "classAnnexBCpdNalAdapterTest.html", null ],
        [ "AnnexBNalAdapterTest", "classAnnexBNalAdapterTest.html", null ],
        [ "AudioCpdParserTest", "classAudioCpdParserTest.html", null ],
        [ "AvccNalAdapterTest", "classAvccNalAdapterTest.html", null ],
        [ "MkvgenApiFunctionalityTest", "classMkvgenApiFunctionalityTest.html", null ],
        [ "MkvgenApiTest", "classMkvgenApiTest.html", null ],
        [ "SpsParserTest", "classSpsParserTest.html", null ]
      ] ],
      [ "StateTestBase", "classStateTestBase.html", [
        [ "StateApiFunctionalityTest", "classStateApiFunctionalityTest.html", null ],
        [ "StateApiTest", "classStateApiTest.html", null ]
      ] ],
      [ "TraceTestBase", "classTraceTestBase.html", [
        [ "TraceApiFunctionalityTest", "classTraceApiFunctionalityTest.html", null ],
        [ "TraceApiTest", "classTraceApiTest.html", null ]
      ] ],
      [ "UtilTestBase", "classUtilTestBase.html", [
        [ "BitReaderFunctionalityTest", "classBitReaderFunctionalityTest.html", null ],
        [ "BitfieldFunctionalityTest", "classBitfieldFunctionalityTest.html", null ],
        [ "Crc32Test", "classCrc32Test.html", null ],
        [ "DirectoryFunctionalityTest", "classDirectoryFunctionalityTest.html", null ],
        [ "DoubleListFunctionalityTest", "classDoubleListFunctionalityTest.html", null ],
        [ "EndiannessFunctionalityTest", "classEndiannessFunctionalityTest.html", null ],
        [ "ExponentialBackoffUtilsTest", "classExponentialBackoffUtilsTest.html", null ],
        [ "FileLoggerTest", "classFileLoggerTest.html", null ],
        [ "FindStringFunctionalityTest", "classFindStringFunctionalityTest.html", null ],
        [ "HashTableFunctionalityTest", "classHashTableFunctionalityTest.html", null ],
        [ "InstrumentedAllocatorsTest", "classInstrumentedAllocatorsTest.html", null ],
        [ "ItoEFunctionalityTest", "classItoEFunctionalityTest.html", null ],
        [ "MathTest", "classMathTest.html", null ],
        [ "SemaphoreFunctionalityTest", "classSemaphoreFunctionalityTest.html", null ],
        [ "SingleListFunctionalityTest", "classSingleListFunctionalityTest.html", null ],
        [ "StackQueueFunctionalityTest", "classStackQueueFunctionalityTest.html", null ],
        [ "StoIFunctionalityTest", "classStoIFunctionalityTest.html", null ],
        [ "StringSearchFunctionalityTest", "classStringSearchFunctionalityTest.html", null ],
        [ "TagsFunctionalityTest", "classTagsFunctionalityTest.html", null ],
        [ "ThreadFunctionalityTest", "classThreadFunctionalityTest.html", null ],
        [ "ThreadpoolFunctionalityTest", "classThreadpoolFunctionalityTest.html", null ],
        [ "ThreadsafeBlockingQueueFunctionalityTest", "classThreadsafeBlockingQueueFunctionalityTest.html", null ],
        [ "TimerQueueFunctionalityTest", "classTimerQueueFunctionalityTest.html", null ],
        [ "TrimStringFunctionalityTest", "classTrimStringFunctionalityTest.html", null ],
        [ "VersionsFunctionalityTest", "classVersionsFunctionalityTest.html", null ]
      ] ],
      [ "ViewTestBase", "classViewTestBase.html", [
        [ "ViewApiFunctionalityTest", "classViewApiFunctionalityTest.html", null ],
        [ "ViewApiTest", "classViewApiTest.html", null ],
        [ "ViewDropPolicyFunctionalityTest", "classViewDropPolicyFunctionalityTest.html", null ]
      ] ]
    ] ],
    [ "TestTransitions", "structTestTransitions.html", null ],
    [ "ThreadpoolUser", "structThreadpoolUser.html", null ],
    [ "TimerEntry", "structTimerEntry.html", null ],
    [ "TimerQueue", "structTimerQueue.html", null ],
    [ "Trace", "structTrace.html", null ],
    [ "TraceProfiler", "structTraceProfiler.html", null ],
    [ "TrackAudioConfig", "structTrackAudioConfig.html", null ],
    [ "TrackCustomData", "unionTrackCustomData.html", null ],
    [ "TrackInfo", "structTrackInfo.html", null ],
    [ "TrackVideoConfig", "structTrackVideoConfig.html", null ],
    [ "ViewItem", "structViewItem.html", null ],
    [ "WindowsThreadRoutineWrapper", "structWindowsThreadRoutineWrapper.html", null ],
    [ "WithParamInterface", null, [
      [ "AcksFunctionalityTest", "classAcksFunctionalityTest.html", null ],
      [ "CallbacksAndPressuresFunctionalityTest", "classCallbacksAndPressuresFunctionalityTest.html", null ],
      [ "ClientFunctionalityTest", "classClientFunctionalityTest.html", null ],
      [ "HybridFileHeapTest", "classHybridFileHeapTest.html", null ],
      [ "HybridHeapTest", "classHybridHeapTest.html", null ],
      [ "IntermittentProducerAutomaticStreamingTest", "classIntermittentProducerAutomaticStreamingTest.html", null ],
      [ "IntermittentProducerFunctionalityTest", "classIntermittentProducerFunctionalityTest.html", null ],
      [ "StateTransitionFunctionalityTest", "classStateTransitionFunctionalityTest.html", null ],
      [ "StreamApiFunctionalityScenarioTest", "classStreamApiFunctionalityScenarioTest.html", null ],
      [ "StreamFunctionalityTest", "classStreamFunctionalityTest.html", null ],
      [ "StreamRecoveryFunctionalityTest", "classStreamRecoveryFunctionalityTest.html", null ],
      [ "StreamStoppingFunctionalityTest", "classStreamStoppingFunctionalityTest.html", null ],
      [ "TokenRotationFunctionalityTest", "classTokenRotationFunctionalityTest.html", null ],
      [ "ViewDropPolicyFunctionalityTest", "classViewDropPolicyFunctionalityTest.html", null ]
    ] ]
];